version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true

  # --- MariaDB
  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - product_db:/var/lib/mysql

  # --- PHP 8.0
  app:
    image: luckykenlin/laravel-app
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./.env.production:/app/.env
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=redis"

  schedule:
    image: luckykenlin/ldp365
    restart: always
    command: /usr/local/etc/php/run-scheduler.sh
    depends_on:
      - app
    volumes:
      - ./.env.production:/app/.env
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=redis"

  # --- nginx
  web:
    image: laravel-web
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:8080"
    depends_on:
      - app
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - ./docker/nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro

  # --- Redis
  redis:
    image: bitnami/redis:6.0
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  product_db:
    driver: local
